export const Categories: string[] = [
  "Cardio",
  "StrengthTraining",
  "Yoga&Pilates",
  "Accessories",
  "Outdoor&Adventure",
  "Recovery&Wellness",
  "Apparel",
  "Nutrition&Supplements",
  "HomeGymEquipment",
  "FitnessTechnology",
  "FunctionalTraining",
  "GroupFitness",
  "WeightManagement",
  "Flexibility&Mobility",
  "AquaticFitness",
];
